branch-defaults:
  master:
    environment: ludotest
  nodemailer:
    environment: ludotest
global:
  application_name: ludo-test
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: ap-southeast-1
  profile: eb-cli
  sc: git
